# <b> Problem 1: Import Pandas and Numpy in the notebook </b>

In [58]:
# Import statements

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# <b> Problem 2 : Load the automobile_data.csv kept in the shared folder

In [59]:
# Mount your drive and read the csv file. Make sure you are using the correct file path

# creating dataframe from the file path
automobile_df = pd.read_csv(r'C:\Users\User\Desktop\asgn work\Python_Data_Analytics_Libraries_Class _3_Assignments\automobile_data.csv')
# print(automobile_df)

# <b> Problem 3 : Do a basic inspection and print the first and last 15 rows of your dataframe

In [60]:
# Your code here

# printing first 15 rows
automobile_df.head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565

In [61]:
# printing last 15 rows
automobile_df.tail(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.4,8.5,90,5500,24,29,9980
191,0,?,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.4,8.5,110,5500,19,24,13295
192,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.4,23.0,68,4500,33,38,13845
193,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.4,9.0,88,5500,25,31,12290
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# <b>Problem 4 : You need to clean the data a little bit now. Replace all column values with the values <code>?</code> and <code>n.a</code> with <code>NaN</code>

In [62]:
# Your code here

# replacing ? and na values with NaN
automobile_df = automobile_df.replace(['?', 'n.a'], np.nan)

# <b>Problem 5 : Print the company name which manufactured the most expensive car. Also print the price of the most expensive car

In [77]:
# Your code here

# dropping null values from dataframe
cleaned_automobile_df = automobile_df.dropna(subset=['price'])

# changing price column datatype from object to int
cleaned_automobile_df['price'] = cleaned_automobile_df['price'].astype('int')

In [78]:
# extracting most expensive car manufacturer and price of most expensive car
cleaned_automobile_df.groupby('make')['price'].max().sort_values(ascending=False).head(1)

make
mercedes-benz    45400
Name: price, dtype: int32

# <b>Problem 6 : Calculate maximum horsepowers for each company. </b>

In [80]:
# Your code here

# converting column horsepower from object to int
cleaned_automobile_df = cleaned_automobile_df.dropna(subset = ['horsepower'])
cleaned_automobile_df['horsepower'] = cleaned_automobile_df['horsepower'].astype('int')

# extracting maximum horsepower for each company
print('Maximum horsepower for each company')
cleaned_automobile_df.groupby('make')['horsepower'].max()

Maximum horsepower for each company

make
alfa-romero      154
audi             140
bmw              182
chevrolet         70
dodge            145
honda            101
isuzu             90
jaguar           262
mazda            135
mercedes-benz    184
mercury          175
mitsubishi       145
nissan           200
peugot           142
plymouth         145
porsche          207
saab             160
subaru           111
toyota           161
volkswagen       110
volvo            162
Name: horsepower, dtype: int32

# <b> Problem 7 : Print the total number of cars manufactured by each company

In [81]:
# Your code here

# extracting total cars made by each company
print('Number of Cars manufactured by each company')
cleaned_automobile_df['make'].value_counts()

Number of Cars manufactured by each company

make
toyota           32
nissan           18
mazda            17
honda            13
mitsubishi       13
volkswagen       12
subaru           12
volvo            11
peugot           11
dodge             9
bmw               8
mercedes-benz     8
plymouth          7
saab              6
audi              6
porsche           4
alfa-romero       3
jaguar            3
chevrolet         3
isuzu             2
mercury           1
Name: count, dtype: int64

# <b> Problem 8 : Create a new column for the updated price. This updated price will be calculated on top of the given price - if the engine is in front, price will be same else if the engine is in rear, price will be doubled </b>

In [85]:
# Your code here. Use apply and lambda

cleaned_automobile_df['updated_price'] = cleaned_automobile_df.apply(lambda row : row['price']*2 if row['engine-location']  == 'rear' else row['price'], axis=1)

# checking whether the price for rear engine location is doubled or not
cleaned_automobile_df[cleaned_automobile_df['engine-location'] == 'rear']

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_price
126,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,mpfi,3.74,2.9,9.5,207,5900,17,25,32528,65056
127,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,mpfi,3.74,2.9,9.5,207,5900,17,25,34028,68056
128,3,NaN,porsche,gas,std,two,convertible,rwd,rear,89.5,...,mpfi,3.74,2.9,9.5,207,5900,17,25,37028,74056

# <b>Problem 9 : Sort the dataframe by car and price columns

In [98]:
# Your code here

# sorting dataframe by car and price
cleaned_automobile_df.sort_values(by = ['make', 'price'], ascending=[True, True])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_price,num_doors
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,13495,13495,2.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,16500,16500,2.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000,19,26,16500,16500,2.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.4,10.0,102,5500,24,30,13950,13950,4.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,3.19,3.4,8.5,110,5500,19,25,15250,15250,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,3.62,3.15,7.5,162,5100,17,22,18950,18950,4.0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,8.7,160,5300,19,25,19045,19045,4.0
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.58,2.87,8.8,134,5500,18,23,21485,21485,4.0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.01,3.4,23.0,106,4800,26,27,22470,22470,4.0
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114,5400,19,25,22625,22625,4.0

# <b> Problem 10 : Create a new column which stores the number of doors in a car as integers.

In [102]:
# Your code here. Use apply

# creating new column num_doors to represent number of doors in integer dtype
cleaned_automobile_df['num_doors'] = cleaned_automobile_df['num-of-doors'].replace({'four':4, 'two':2})

num-of-doors
four    112
two      85
Name: count, dtype: int64

# <b>Problem 11 : Concatenate the two data frames given below firstly row wise and secondly column wise.</b>

<code>GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}</code>

<code>japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}</code>

In [117]:
# Your code here
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

german_cars_df = pd.DataFrame(GermanCars)

japanese_cars_df = pd.DataFrame(japaneseCars)

# concatenating two dataframes row wise
pd.concat((german_cars_df, japanese_cars_df), ignore_index=True, axis=0)

# concatenating two dataframes column wise
pd.concat((german_cars_df, japanese_cars_df), keys= ['German', 'Japanese'], axis=1)

     German             Japanese
    Company   Price      Company  Price
0      Ford   23845       Toyota  29995
1  Mercedes  171995        Honda  23600
2       BMV  135925       Nissan  61500
3      Audi   71400  Mitsubishi   58900